---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - cloudwatch_region is defined
      - cloudwatch_log_group is defined
      - domain_name is defined
      - backup_day is defined

- name: Create the data directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data"
    state: directory

- name: Create the logs directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/logs"
    state: directory

- name: Create the config directory
  file:
    path: "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/config"
    state: directory

- name: Create app container
  docker_container:
    name: "gitlab-app"
    image: "gitlab/gitlab-ce:latest"
    restart_policy: "always"
    log_driver: "awslogs"
    log_options:
        awslogs-region: "{{cloudwatch_region}}"
        awslogs-group: "{{cloudwatch_log_group}}"
        awslogs-stream: "{{application_name}}"
    exposed_ports:
      - "80"
    volumes:
        - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/config:/etc/gitlab"
        - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/logs:/var/log/gitlab"
        - "{{ hostvars[inventory_hostname].working_directory }}{{ application_name }}/files/data:/var/opt/gitlab"
    env:
      VIRTUAL_HOST: "{{ domain_name }}"
      LETSENCRYPT_HOST: "{{ domain_name }}"
      VIRTUAL_PORT: "80"

- name: Setup file backups
  include_role:
    name: namelivia.backups
    tasks_from: setup-file-backups

- include_role:
    name: namelivia.backups
    tasks_from: setup-s3-backups
